In [3]:
import pandas as pd
from pandas import DataFrame

df:DataFrame = pd.read_csv('各鄉鎮市區人口密度.csv')
df1 = df.drop(index=0)
df2 = df1.rename(columns={'statistic_yyy':'統計年',
    'site_id':'區域別',
    'people_total':'年底人口數',
    'area':'土地面積',
    'population_density':'人口密度'})
df3 = df2.dropna()
df4 = df3.replace('… ',0)
df4['年底人口數'] = df4['年底人口數'].astype(int)
df4['土地面積'] = df4['土地面積'].astype(float)
df4['人口密度'] = df4['人口密度'].astype(int)

def get_area(value:str) -> str:
    if len(value)>4:
        return value[:3]
    else:
        return value


df4['縣市'] = df4['區域別'].apply(get_area)
def delete_area(value:str,n) -> str:
    if len(value)>n:
        return value[-3:]
    else:
        return value

df4['區域別'] = df4['區域別'].apply(delete_area,n=4)
df4

     統計年   區域別   年底人口數     土地面積   人口密度    縣市
1    106   板橋區  551480  23.1373  23835   新北市
2    106   三重區  387484  16.3170  23747   新北市
3    106   中和區  413590  20.1440  20532   新北市
4    106   永和區  222585   5.7138  38956   新北市
5    106   新莊區  416524  19.7383  21102   新北市
..   ...   ...     ...      ...    ...   ...
366  106   北竿鄉    2360   9.9000    238   連江縣
367  106   莒光鄉    1624   4.7000    346   連江縣
368  106   東引鄉    1352   3.8000    356   連江縣
369  106  東沙群島       0   2.3800      0  東沙群島
370  106  南沙群島       0   0.5045      0  南沙群島

[370 rows x 6 columns]

In [5]:
df5 = df4.set_index(['縣市','區域別'])
df5

           統計年   年底人口數     土地面積   人口密度
縣市   區域別
新北市  板橋區   106  551480  23.1373  23835
     三重區   106  387484  16.3170  23747
     中和區   106  413590  20.1440  20532
     永和區   106  222585   5.7138  38956
     新莊區   106  416524  19.7383  21102
...        ...     ...      ...    ...
連江縣  北竿鄉   106    2360   9.9000    238
     莒光鄉   106    1624   4.7000    346
     東引鄉   106    1352   3.8000    356
東沙群島 東沙群島  106       0   2.3800      0
南沙群島 南沙群島  106       0   0.5045      0

[370 rows x 4 columns]

In [6]:
df5.reset_index()

       縣市   區域別  統計年   年底人口數     土地面積   人口密度
0     新北市   板橋區  106  551480  23.1373  23835
1     新北市   三重區  106  387484  16.3170  23747
2     新北市   中和區  106  413590  20.1440  20532
3     新北市   永和區  106  222585   5.7138  38956
4     新北市   新莊區  106  416524  19.7383  21102
..    ...   ...  ...     ...      ...    ...
365   連江縣   北竿鄉  106    2360   9.9000    238
366   連江縣   莒光鄉  106    1624   4.7000    346
367   連江縣   東引鄉  106    1352   3.8000    356
368  東沙群島  東沙群島  106       0   2.3800      0
369  南沙群島  南沙群島  106       0   0.5045      0

[370 rows x 6 columns]

In [7]:
df5[['年底人口數','土地面積']].unstack(level='縣市')

    年底人口數                                                       ...     土地面積  \
縣市    南投縣 南沙群島 嘉義市 嘉義縣      基隆市      宜蘭縣 屏東縣 彰化縣       新北市 新竹市  ...      臺中市
區域別                                                             ...
七堵區   NaN  NaN NaN NaN  53972.0      NaN NaN NaN       NaN NaN  ...      NaN
七美鄉   NaN  NaN NaN NaN      NaN      NaN NaN NaN       NaN NaN  ...      NaN
七股區   NaN  NaN NaN NaN      NaN      NaN NaN NaN       NaN NaN  ...      NaN
三峽區   NaN  NaN NaN NaN      NaN      NaN NaN NaN  114926.0 NaN  ...      NaN
三星鄉   NaN  NaN NaN NaN      NaN  21467.0 NaN NaN       NaN NaN  ...      NaN
..    ...  ...  ..  ..      ...      ...  ..  ..       ...  ..  ...      ...
鼓山區   NaN  NaN NaN NaN      NaN      NaN NaN NaN       NaN NaN  ...      NaN
龍井區   NaN  NaN NaN NaN      NaN      NaN NaN NaN       NaN NaN  ...  38.0377
龍崎區   NaN  NaN NaN NaN      NaN      NaN NaN NaN       NaN NaN  ...      NaN
龍潭區   NaN  NaN NaN NaN      NaN      NaN NaN NaN       NaN NaN  ...      NaN
龜山區   NaN  NaN NaN NaN      NaN      NaN NaN NaN       NaN NaN  ...      NaN


縣市  臺北市       臺南市 臺東縣 花蓮縣 苗栗縣 連江縣 金門縣 雲林縣      高雄市
區域別
七堵區 NaN       NaN NaN NaN NaN NaN NaN NaN      NaN
七美鄉 NaN       NaN NaN NaN NaN NaN NaN NaN      NaN
七股區 NaN  110.1492 NaN NaN NaN NaN NaN NaN      NaN
三峽區 NaN       NaN NaN NaN NaN NaN NaN NaN      NaN
三星鄉 NaN       NaN NaN NaN NaN NaN NaN NaN      NaN
..   ..       ...  ..  ..  ..  ..  ..  ..      ...
鼓山區 NaN       NaN NaN NaN NaN NaN NaN NaN  14.7523
龍井區 NaN       NaN NaN NaN NaN NaN NaN NaN      NaN
龍崎區 NaN   64.0814 NaN NaN NaN NaN NaN NaN      NaN
龍潭區 NaN       NaN NaN NaN NaN NaN NaN NaN      NaN
龜山區 NaN       NaN NaN NaN NaN NaN NaN NaN      NaN

[359 rows x 48 columns]

In [ ]:
#groupby的實體可以[] -> 選擇欄位
#groupby的實體.統計的functiom
df5.groupby(level='縣市')[['年底人口數','土地面積']].sum()